- name: Install PHP packages
  sudo: yes
  apt:  package=php5-cgi state=latest  

#- name: Set doc_root cgi
#  sudo: yes
#  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^doc_root" line="doc_root=/home/vagrant"

- name: Set cgi.force_redirect cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^cgi.force_redirect" line="cgi.force_redirect=0"

- name: Set register_globals cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^register_globals" line="register_globals=Off"

- name: Set session.auto_start cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^session.auto_start" line="session.auto_start=Off"

- name: Set magic_quotes_gpc cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^magic_quotes_gpc" line="magic_quotes_gpc=Off"

- name: Set date.timezone cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^date.timezone" line="date.timezone=Europe/Madrid"

- name: Set upload_max_filesize
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^upload_max_filesize" line="upload_max_filesize = 30M"
  
- name: Set post_max_size cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^post_max_size" line="post_max_size = 30M"
  
- name: Set memory_limit cgi
  sudo: yes
  lineinfile: dest=/etc/php5/cgi/php.ini regexp="^memory_limit" line="memory_limit = 256M"  