---
- hosts: webservers
  sudo:  true
  vars:            
    sys_packages:  
      - acl    
      - vim  
      - default-jdk  
      - unzip        
    php_packages:      
      - { name: pear, package: php-pear }
      #- { name: xdebug, package: php5-xdebug }
      - { name: curl, package: php5-curl }
      - { name: mcrypt, package: php5-mcrypt }
      - { name: mysql, package: php5-mysql }
      - { name: mysql, package: php5-cli }
      - { name: mysql, package: php5-json }
      - { name: mysql, package: php5-intl }
      - { name: mysql, package: php5-sqlite }
      - { name: mysql, package: php5-xmlrpc }
      - { name: mysql, package: php5-gd }
      - { name: apc, package: php-apc }      
              
  roles:
    - init
    - perfmon    
    - php5        

- hosts: yaws
  sudo: true  
  roles:
    - yaws

- hosts: nginx
  sudo: true
  roles:
    - nginx

- hosts: apache
  sudo: true
  roles: 
    - apache

- hosts: apache_phpmodule
  sudo: true
  roles: 
    - apache-php-mod

- hosts: apache_fastcgi
  sudo: true
  roles: 
    - apache-fastcgi

- hosts: cgi
  sudo: true
  roles:
    - php5-cgi

- hosts: fastcgi
  sudo: true
  roles:
    - php5-fpm

- hosts: webservers
  sudo: true
  roles:
    - symfony_apps
