---
  - name: Install yaws
    sudo: yes
    apt:  pkg={{ item }} state=latest
    with_items: yaws
  
  - name: Add virtual hosts localhost
    sudo: yes
    template: src=localhost-{{tipoCgi}}.tpl dest=/etc/yaws/conf.d/localhost.conf owner=root mode=0644
    notify: restart yaws

  - name: Add virtual hosts localhost
    sudo: yes
    template: src=symfony-{{tipoCgi}}.tpl dest=/etc/yaws/conf.d/symfony.conf owner=root mode=0644 
    notify: restart yaws